AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  EcsAmiId:
    Type: String
    Description: ECS AMI id
  EcsInstanceType:
    Type: String
    Description: ECS EC2 instance type
    Default: t2.small
  KeyName:
    Type: String
    Description: Name of existing EC2 KeyPair for SSH to servers
    Default: devops
  VpcId:
    Type: String
    Description: VPC Id of existing VPC
    AllowedPattern: "^(?:vpc-[0-9a-f]*)$"
    Default: vpc-0ef54368bc85768ff
  SubnetIds:
    Type: CommaDelimitedList
    Description: Comma separated list of existing VPC Subnet Ids
    Default: "subnet-03540c8937acb1963,subnet-0dc2017d2cfe64e01"
  AsgMaxSize:
    Type: Number
    Description: Maxium size of ECS Cluster Auto Scaler. To be safe this should be double
      the current size so the rolling update has plenty of room to spin up new instances
  AsgMinSize:
    Type: Number
    Description: Minium size of ECS Cluster Auto Scaler
  AsgInitialSize:
    Type: Number
    Description: Initial desired size of ECS Cluster Auto Scaler. When doing a rolling update
      this should be set to be the current size of the auto scaling group.
  MinInstancesInServiceDuringUpdate:
    Type: Number
    Description: During a rolling update of the autoscaling group this value determines
      how many instances should be kept up and running. It seems this number needs to be
      large enough for ECS to keep all of the current services running. Otherwise the
      instances are not terminated which prevents the rolling update from progressing as
      the cloudformation rolling update code expects
  EcsClusterName:
    Type: String
    Description: ECS Cluster Name
  Environment:
    Type: String
    Description: Propigate this as a tag on created AWS resources
  NewRelicLicenceKey:
    Type: String
    Description: Licence key to enable new relic server monitoring
  IAMGroupsForSSH:
    Type: String
    Description: Comma seperated list of IAM Groups. Users in these groups that have
      a ssh public key set in IAM will be able to ssh into the ec2 instances in the cluster
  SSHScriptVersion:
    Type: String
    Description: tag or branch of https://github.com/concord-consortium/aws-ec2-ssh
      which handles the accessing public keys for ssh users
    Default: v1.3.0-cc.1
  PortalDockerAuthData:
    Type: String
    Description: 'a json object with the configuration for docker hub. Something like :
      {"https://index.docker.io/v1/":{"username":"[username]", "password":"[password]","email":"email@example.com"}}'

Resources:
  EcsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "ECS Allowed Ports - ${EcsClusterName}"
      VpcId: !Ref "VpcId"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      Tags:
      - Key: Contact
        Value: scytacki
      - Key: Environment
        Value: !Ref 'Environment'

  EcsInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Principal:
            Service: "ec2.amazonaws.com"
          Action: "sts:AssumeRole"
      ManagedPolicyArns:
      - 'arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role'

  # this was taken from https://github.com/concord-consortium/aws-ec2-ssh/blob/master/showcase.yaml
  SSHLocalRolePolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: iam
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - 'iam:ListUsers'
          - 'iam:GetGroup'
          Resource: '*'
        - Effect: Allow
          Action:
          - 'iam:ListSSHPublicKeys'
          - 'iam:GetSSHPublicKey'
          Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:user/*'
        - Effect: Allow
          Action: 'ec2:DescribeTags'
          Resource: '*'
      Roles:
        - !Ref EcsInstanceRole

  EcsInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
      - !Ref EcsInstanceRole

  EcsInstanceLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref "EcsAmiId"
      InstanceType: !Ref "EcsInstanceType"
      AssociatePublicIpAddress: true
      # TODO need to look this up
      IamInstanceProfile: !Ref EcsInstanceProfile
      KeyName: !Ref "KeyName"
      SecurityGroups: [ !Ref "EcsSecurityGroup" ]
      UserData:
        # NOTE the termination lambda fuction currently parses this UserData looking
        # for the ECS_CLUSTER so the cluster name needs to not be in quotes
        # a better approach in the future would be to pass an ENV var to the lambda
        # function specifying the cluster
        Fn::Base64: !Sub |
          #!/bin/bash
          echo ECS_CLUSTER=${EcsClusterName} >> /etc/ecs/ecs.config
          echo ECS_ENGINE_AUTH_TYPE=docker >> /etc/ecs/ecs.config
          echo ECS_ENGINE_AUTH_DATA='${PortalDockerAuthData}' >> /etc/ecs/ecs.config
          rpm -Uvh https://yum.newrelic.com/pub/newrelic/el5/x86_64/newrelic-repo-5-3.noarch.rpm
          yum install -y aws-cfn-bootstrap newrelic-sysmond git aws-cli
          nrsysmond-config --set license_key=${NewRelicLicenceKey}
          service newrelic-sysmond start
          groupadd -r docker
          usermod -a -G docker newrelic
          service docker restart
          service newrelic-sysmond restart
          # Setup iam ssh access
          tmpdir=$(mktemp -d)
          cd "$tmpdir"
          git clone --branch ${SSHScriptVersion} --depth 1 https://github.com/concord-consortium/aws-ec2-ssh
          cd aws-ec2-ssh
          sudo ./install.sh -i "${IAMGroupsForSSH}" -s "${IAMGroupsForSSH}"
          # notify cloudformation
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource EcsInstanceAutoScaleGroup --region ${AWS::Region}

  EcsInstanceAutoScaleGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: !Ref "SubnetIds"
      LaunchConfigurationName: !Ref "EcsInstanceLaunchConfig"
      MetricsCollection:
        - Granularity: "1Minute"
      MinSize: !Ref AsgMinSize
      MaxSize: !Ref AsgMaxSize
      DesiredCapacity: !Ref "AsgInitialSize"
      NotificationConfigurations:
      - TopicARN: !Ref "AutoScaleSNSTopic"
        NotificationTypes:
        - autoscaling:EC2_INSTANCE_LAUNCH
        - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
        - autoscaling:EC2_INSTANCE_TERMINATE
        - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
      Tags:
      - Key: Contact
        Value: scytacki
        PropagateAtLaunch: true
      - Key: Environment
        Value: !Ref "Environment"
        PropagateAtLaunch: true
      - Key: Name
        Value: !Sub "ECS ${EcsClusterName}"
        PropagateAtLaunch: true
      - Key: Description
        Value: !Sub |
          This instance is the part of an Auto Scaling group for an ECS cluster. These
          resources were all created by the Cloud Formation stack ${AWS::StackName}
        PropagateAtLaunch: true
    # A rolling update is needed so the autoscaler uses the termination lifecycle of the
    # instances. That way the lambda function can move the tasks to the new instance.
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinSuccessfulInstancesPercent: "80"
        # this will make it wait on the cfn-signal above before marking the instance
        # as successful
        WaitOnResourceSignals: true
        MinInstancesInService: !Ref MinInstancesInServiceDuringUpdate
        PauseTime: PT5M
        SuspendProcesses:
        - AlarmNotification
        - ScheduledActions
        - HealthCheck
        - ReplaceUnhealthy
        - AZRebalance
      AutoScalingScheduledAction:
        IgnoreUnmodifiedGroupSizeProperties: 'true'

  EcsCluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: !Ref "EcsClusterName"

  # taken from:  https://github.com/awslabs/ecs-cid-sample
  SNSLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: [autoscaling.amazonaws.com]
            Action: [ "sts:AssumeRole" ]
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AutoScalingNotificationAccessRole
      Path: "/"

  # taken from:  https://github.com/awslabs/ecs-cid-sample
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Policies:
        - PolicyName: "lambda-inline"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                - autoscaling:CompleteLifecycleAction
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                - ec2:DescribeInstances
                - ec2:DescribeInstanceAttribute
                - ec2:DescribeInstanceStatus
                - ec2:DescribeHosts
                - ecs:ListContainerInstances
                - ecs:SubmitContainerStateChange
                - ecs:SubmitTaskStateChange
                - ecs:DescribeContainerInstances
                - ecs:UpdateContainerInstancesState
                - ecs:ListTasks
                - ecs:DescribeTasks
                - sns:Publish
                - sns:ListSubscriptions
                Resource: "*"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: [ "sts:AssumeRole" ]
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AutoScalingNotificationAccessRole
      Path: "/"

  # taken from:  https://github.com/awslabs/ecs-cid-sample
  AutoScaleSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !GetAtt [AutoScaleLambdaFunction, Arn]
          Protocol: lambda
    DependsOn: AutoScaleLambdaFunction

  # taken from:  https://github.com/awslabs/ecs-cid-sample
  AutoScaleLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: concordqa-devops
        S3Key: "ecs-autoscale-lamba/index.zip"
      Description: Lambda code for the autoscaling hook triggers invoked when autoscaling events of launching and terminating instance occur
      Handler: "index.lambda_handler"
      Role: !GetAtt [LambdaExecutionRole, Arn]
      Runtime: "python2.7"
      Timeout: "300"

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AutoScaleLambdaFunction
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn: !Ref AutoScaleSNSTopic

  AutoScaleTerminateHook:
    Type: AWS::AutoScaling::LifecycleHook
    Properties:
      AutoScalingGroupName: !Ref EcsInstanceAutoScaleGroup
      DefaultResult: ABANDON
      HeartbeatTimeout: "900"
      LifecycleTransition: autoscaling:EC2_INSTANCE_TERMINATING
      NotificationTargetARN: !Ref AutoScaleSNSTopic
      RoleARN: !GetAtt [SNSLambdaRole, Arn]
    DependsOn: AutoScaleSNSTopic

  # autoscaling rules and setup
  # we might want to change this to stepadjustments instead of just a simple
  # scaling adjustment
  CPUReservationScaleUpPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref EcsInstanceAutoScaleGroup
      # Step scaling skips any cooldown period. As long as the difference between the
      # desired capacity and the current capacity matches the scaling adjustment then no
      # new scaling action will be taken.
      PolicyType: StepScaling
      # give the instance a minute before it is part of the total metrics, I believe
      # this also delays the start of future scaleup events. We aren't using the
      # autoscaler's metrics though, we are using the ECS cluster metric which will update
      # instantly as soon as the instance registers itself with ECS.
      EstimatedInstanceWarmup: '60'
      StepAdjustments:
        # from 66% to 76% scale up by one
        - MetricIntervalLowerBound: 0
          MetricIntervalUpperBound: 10
          ScalingAdjustment: '1'
        # from 76% to 100% scale up by two
        - MetricIntervalLowerBound: 10
          ScalingAdjustment: '2'

  CPUReservationHighAlert:
    Type: AWS::CloudWatch::Alarm
    Properties:
      EvaluationPeriods: '1'
      Statistic: Maximum
      # CPU reservation is across the whole cluster, so with a period of 60 the max, min
      # and average will all be the same. There is no built in way to get per instance
      # CPUReservation. If we had that it would give us better
      # flexibilty if we have a hetrogenous set of tasks running.
      Threshold: '66'
      Period: '60'
      AlarmActions:
      - !Ref CPUReservationScaleUpPolicy
      Dimensions:
      - Name: ClusterName
        Value: !Ref EcsCluster
      ComparisonOperator: GreaterThanOrEqualToThreshold
      MetricName: CPUReservation
      Namespace: AWS/ECS

  CPUReservationScaleDownPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref EcsInstanceAutoScaleGroup
      # Step scaling skips any cooldown period. As long as the difference between the
      # desired capacity and the current capacity matches the scaling adjustment then no
      # new scaling action will be taken. This seems to cause problems for us because the
      # the CPUReservation does not update instantly, which leads to a second
      # incorrect scale down. However because there is no cooldown period this problem
      # is corrected quickly as long as the extra decrease causes a scale up alarm.
      PolicyType: StepScaling
      StepAdjustments:
        - MetricIntervalUpperBound: 0
          ScalingAdjustment: '-1'

  CPUReservationLowAlert:
    Type: AWS::CloudWatch::Alarm
    Properties:
      EvaluationPeriods: '5'
      Statistic: Average
      Threshold: '25'
      Period: '60'
      AlarmActions:
      - !Ref CPUReservationScaleDownPolicy
      Dimensions:
      - Name: ClusterName
        Value: !Ref EcsCluster
      ComparisonOperator: LessThanOrEqualToThreshold
      MetricName: CPUReservation
      Namespace: AWS/ECS

Outputs:
  ClusterName:
    Description: The name of the cluster created here
    Value: !Ref EcsClusterName
    Export:
      Name: !Sub "${AWS::StackName}-ClusterName"
  ClusterSecurityGroupId:
    Description: EC2 Security group id of the EC2 instances in the cluster
    Value: !Ref EcsSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-ClusterSecurityGroupId"