AWSTemplateFormatVersion: 2010-09-09
Description: Token service resources

Parameters:
  Environment:
    Type: String
    Description: Lowercase name of environment (either staging or production)
    Default: staging
    AllowedValues:
      - staging
      - production
  BucketsListable:
    Type: CommaDelimitedList
  BucketsReadableAndWritable:
    Description: S3 Buckets that contents that are both readable and writable
    Type: CommaDelimitedList
  BucketsReadable:
    Type: CommaDelimitedList
    Description: S3 Buckets that have contents that are readable

Resources:
  TokenServiceUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "token-service-${Environment}"
  TokenServiceKey:
    Type: AWS::IAM::AccessKey
    DependsOn: TokenServiceUser
    Properties:
      UserName: !Sub "token-service-${Environment}"
      Serial: 1
      Status: Active
  TokenServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "token-service-${Environment}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !GetAtt [TokenServiceUser, Arn]
            Action:
              - sts:AssumeRole
      Description: !Sub "All needed S3 actions on token-service-${Environment}"
      MaxSessionDuration: 3600
  TokenServicePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "token-service-${Environment}"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowListing
            Effect: Allow
            Action:
              - s3:ListBucket
              - s3:ListBucketVersions
            # TODO: use https://stackoverflow.com/a/66425178
            Resource: !Ref BucketsListable
          - Sid: AllowReadAndWrite
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:GetObjectVersion
              - s3:DeleteObject
              - s3:DeleteObjectVersion
            Resource: !Ref BucketsReadableAndWritable
          - Sid: AllowOnlyRead
            Effect: Allow
            Action:
              - s3:GetObject
            Resource: !Ref BucketsReadable
          - Sid: AllowListExecutions
            Effect: Allow
            Action:
              - athena:ListQueryExecutions
              - athena:GetQueryExecution
            Resource:
              - !Sub "arn:aws:athena:us-east-1:${AWS::AccountId}:workgroup/*"
      Roles:
        - !Ref TokenServiceRole

Outputs:
  AccessKey:
    Description: Access key of the token-service user
    Value: !Ref TokenServiceKey
  SecretKey:
    Description: Secret key of the token-service user
    Value: !GetAtt [TokenServiceKey, SecretAccessKey]
  RoleArn:
    Description: Arn of token service role
    Value: !GetAtt [TokenServiceRole, Arn]
