# Name of the new stack to create
Name: 'test-stack'
# YAML cloudformation template for this new stack
Template: 'portal-app-only.yml'
# The parameters from the original stack will be used as the defaults
OriginalStack: 'learn-ecs-staging'
# Modifications to the original stack's parameters
# Any parameters not specified in the Template will be automatically removed
ParameterModifications:
  # 12 char or less name prepended to some AWS resources
  ShortName: 'TestStack'
  # Version of the portal to use
  PortalDockerImage: 'concordconsortium/rigse:v1.33.0'
  # Route53 domain name
  DomainName: 'test-stack.staging.concord.org'
  # Unique log group in cloudwatch
  CloudWatchLogGroup: 'test-stack'
  # URL used by Portal in email messages and return urls sent to LARA
  SiteURL: 'https://test-stack.staging.concord.org'
  # This is the host name of the internal load balancer setup by the main
  # stack.  You can find it in the Outputs of the InternalLoadBalancerStack. It is the
  # ELBDNSName property.
  SolrLoadBalancerHostName: 'Replace Me'
