# Name of the new stack to create
# For a LARA stack this has to be 16 chars or less because this name
# is prepended to the stack id for some resources
Name: 'lara-int-test'
# YAML cloudformation template for this new stack
Template: 'lara-ecs.yml'
# The parameters from the original stack will be used as the defaults
OriginalStack: 'lara-qa'
# Modifications to the original stack's parameters
# Any parameters not specified in the Template will be automatically removed
ParameterModifications:
  # Version of lara to use
  # LaraDockerImage: 'concordconsortium/rigse:v1.33.0'
  # First part of hostname is added to the DomainName property
  HostName: 'lara-interactives-test'
  # Unique log group in cloudwatch
  CloudWatchLogGroup: 'lara-interactives-test'
